package UserInterfaces;

import Bussiness.TicketManager;
import Bussiness.UserManager;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

public class GetTicket extends javax.swing.JDialog {

    UserManager userManager = new UserManager();
    TicketManager ticketManager = new TicketManager();
    
    private String blank = "";
    private String notEnoughTickets = "No hay suficientes tiquetes";
    private String noTickets = "No hay tiquetes con estas caracteristicas";
    
    int currentTicketID = -1;

    public GetTicket(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

        initialSetUp();

        restart();
    }

    private void fillComboBox(JComboBox comboToFill, ArrayList<String> filling) {
        for (String line : filling) {
            comboToFill.addItem(line);
        }
    }

    private ArrayList<String> makeArray(String[] list) {
        ArrayList<String> locationArray = new ArrayList();
        for (String line : list) {
            locationArray.add(line);
        }
        return locationArray;
    }

    private void initialSetUp() {
        lblError.setText(blank);
        fillComboBox(comboUsers, userManager.getUserList());
        fillComboBox(comboLocations, makeArray(ticketManager.getLocations()) );
        fillComboBox(comboSponsors, makeArray(ticketManager.getSponsors()) );
    }

    
    private void updatePrice() {
        lblError.setText(blank);
        int amountTickets = Integer.parseInt( numberTickets.getModel().getValue().toString() );
        String location = comboLocations.getSelectedItem().toString();
        String sponsor = comboSponsors.getSelectedItem().toString();
        currentTicketID = ticketManager.getTicketID(sponsor, location);
        
        if (currentTicketID == -1) {
            lblError.setText(noTickets);
        } else {
            if (amountTickets > ticketManager.getTicketAmount(currentTicketID)) {
                lblError.setText(notEnoughTickets);
            } else {
                int price = ticketManager.getTicketPrice(currentTicketID) * amountTickets;
                lblTotal.setText(price + "");
                lblError.setText(blank);
            }
        }
        
        
    }
    
    public void restart(){
        lblTotal.setText("0.0");
    }
    
    private void confirmPurchase(){
        ticketManager.purchaseTicket(currentTicketID, Integer.parseInt( numberTickets.getModel().getValue().toString() ), currentTicketID, Integer.parseInt(lblTotal.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        comboLocations = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        numberTickets = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        comboUsers = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboSponsors = new javax.swing.JComboBox<>();
        btnGetTotal = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        Start = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 148, 148));
        jPanel4.setForeground(new java.awt.Color(0, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 245, 245));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TICKET");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 150, 60));

        jLabel4.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(245, 245, 245));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("now");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 50, 30));

        jLabel5.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(245, 245, 245));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("my");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 60));

        jPanel2.setBackground(new java.awt.Color(0, 181, 181));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Kefa", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Pamela Murillo Anchia");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 160, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 900, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotal.setFont(new java.awt.Font("Hiragino Sans", 1, 36)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal.setText("0.000");
        jPanel3.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 400, 60));

        comboLocations.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        comboLocations.setForeground(new java.awt.Color(0, 0, 0));
        comboLocations.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboLocationsItemStateChanged(evt);
            }
        });
        jPanel3.add(comboLocations, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 210, 40));

        jPanel1.setBackground(new java.awt.Color(240, 240, 240));
        jPanel1.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Hiragino Mincho ProN", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Compra de boletos");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 220, 30));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 80));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 900, 10));

        numberTickets.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        numberTickets.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        numberTickets.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numberTicketsStateChanged(evt);
            }
        });
        jPanel3.add(numberTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 80, 40));

        jLabel9.setFont(new java.awt.Font("Hiragino Sans", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Entradas a comprar");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 210, 30));

        comboUsers.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        jPanel3.add(comboUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 210, 40));

        jLabel10.setFont(new java.awt.Font("Hiragino Sans", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Localidad:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 210, 30));

        jLabel11.setFont(new java.awt.Font("Hiragino Sans", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Su Total es:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 230, 60));

        btnConfirm.setFont(new java.awt.Font("Hiragino Sans", 1, 24)); // NOI18N
        btnConfirm.setText("Confirmar");
        btnConfirm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });
        jPanel3.add(btnConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 170, 60));

        lblError.setFont(new java.awt.Font("Hiragino Sans", 1, 18)); // NOI18N
        lblError.setForeground(new java.awt.Color(204, 0, 0));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setText("No existen boletos con estas caracteristicas");
        jPanel3.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 410, 30));

        jLabel13.setFont(new java.awt.Font("Hiragino Sans", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Patrocinador:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 210, 30));

        comboSponsors.setFont(new java.awt.Font("Hiragino Sans", 0, 18)); // NOI18N
        comboSponsors.setForeground(new java.awt.Color(0, 0, 0));
        comboSponsors.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboSponsorsItemStateChanged(evt);
            }
        });
        jPanel3.add(comboSponsors, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 210, 40));

        btnGetTotal.setFont(new java.awt.Font("Hiragino Sans", 1, 24)); // NOI18N
        btnGetTotal.setText("Mostar Total");
        btnGetTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnGetTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetTotalActionPerformed(evt);
            }
        });
        jPanel3.add(btnGetTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 170, 60));

        jLabel14.setFont(new java.awt.Font("Hiragino Sans", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Seleccione su numero de cedula:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 310, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 900, 460));

        Start.setText("Inicio");

        jMenuItem3.setText("Comprar entradas");
        Start.add(jMenuItem3);

        menuBar.add(Start);

        jMenu1.setText("Reportes");

        jMenuItem4.setText("Reporte 1");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Reporte 2");
        jMenu1.add(jMenuItem5);

        menuBar.add(jMenu1);

        jMenu2.setText("CRUD");

        jMenuItem1.setText("De Usuarios");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("De Boletos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        restart();
        confirmPurchase();
        
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void comboLocationsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboLocationsItemStateChanged

    }//GEN-LAST:event_comboLocationsItemStateChanged

    private void numberTicketsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numberTicketsStateChanged
        
    }//GEN-LAST:event_numberTicketsStateChanged

    private void comboSponsorsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboSponsorsItemStateChanged

    }//GEN-LAST:event_comboSponsorsItemStateChanged

    private void btnGetTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetTotalActionPerformed
        updatePrice();
    }//GEN-LAST:event_btnGetTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GetTicket dialog = new GetTicket(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Start;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnGetTotal;
    private javax.swing.JComboBox<String> comboLocations;
    private javax.swing.JComboBox<String> comboSponsors;
    private javax.swing.JComboBox<String> comboUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JSpinner numberTickets;
    // End of variables declaration//GEN-END:variables
}
